/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/B2aerZGlup6
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export default function PropertyPost() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Property information</CardTitle>
        <CardDescription>Enter the details of the property you&apos;re listing.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid md:grid-cols-2 gap-4">
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="price">Price</Label>
            <Input id="price" placeholder="$" type="number" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="beds">Beds</Label>
            <Input id="beds" placeholder="Beds" type="number" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="baths">Baths</Label>
            <Input id="baths" placeholder="Baths" type="number" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="type">Type</Label>
            <Select>
              <SelectTrigger id="type">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="house">House</SelectItem>
                <SelectItem value="apartment">Apartment</SelectItem>
                <SelectItem value="townhouse">Townhouse</SelectItem>
                <SelectItem value="condo">Condo</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="transaction">Transaction</Label>
            <Select>
              <SelectTrigger id="transaction">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="rent">For Rent</SelectItem>
                <SelectItem value="sell">For Sale</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="flex flex-col space-y-1.5">
          <Label htmlFor="address">Address</Label>
          <Input id="address" placeholder="123 Main St" />
        </div>
        <div className="flex flex-col space-y-1.5">
          <Label htmlFor="apartment">Apartment, suite, etc.</Label>
          <Input id="apartment" placeholder="Apartment, suite, etc." />
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="city">City</Label>
            <Input id="city" placeholder="City" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="state">State</Label>
            <Input id="state" placeholder="State" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="zip">ZIP code</Label>
            <Input id="zip" placeholder="ZIP code" />
          </div>
        </div>
        <div className="flex flex-col space-y-1.5">
          <Label htmlFor="listing">Listed by</Label>
          <Input id="listing" placeholder="Person or agency listing the property" />
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="images">Upload Images</Label>
            <Input accept="image/*" id="images" type="file" />
          </div>
          <div className="flex flex-col space-y-1.5">
            <Label htmlFor="videos">Upload Videos</Label>
            <Input accept="video/*" id="videos" type="file" />
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <Button size="sm">Save</Button>
      </CardFooter>
    </Card>
  )
}
